language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
script:
  - "nosetests --verbose test"
  - "pep8 --show-source hiera test"
notifications:
  email: thomas.vandoren@gmail.com
matrix:
  allow_failures:
    - python: "3.3"
